### ISSUE TITLE
Some problems with PKU-MMD dataset

### ISSUE THREAD

**Issue by kaai520** [YujieOuO/SMIE#1]
Thanks for your nice work！ I still have some problems with PKU-MMD dataset: 1) PKU-MMD has 2 parts. Which part did you use in the experiments? 2) Are the checkpoints (split_7.pt ~ split_9.pt) trained on PKU-MMD part1?

**Comment by kaai520** [comment]
Looking forward to your reply! Thanks.

**Comment by YujieOuO** [comment]
> Looking forward to your reply! Thanks.

yes，PKU Part1 contains long sequences in 51 action categories, so we conducted experiments on it.
