### ISSUE TITLE
How to generate prompts via ChatGPT?

### ISSUE THREAD

**Issue by kaai520** [YujieOuO/SMIE#2]
I am very interested in the descriptions in ntu120_des.txt. What prompts do you use via ChatGPT to generate them? Can you give an example? Looking forward to your sharing. Thanks.

**Comment by YujieOuO** [comment]
We only have a limitation on the generated character length during the process, for instance:  Describe the action named 'Drink water,' less than 40 words. You can try a more detailed prompt to obtain a more accurate description of the action. In my experience, this approach tends to get better results.

**Comment by chuanshen-chen** [comment]
Thanks a lot!

**Comment by kaai520** [comment]
Thanks a lot!
