### ISSUE TITLE
Alternative ways to download datasets

### ISSUE THREAD

**Issue by JackChen890311** [YujieOuO/SMIE#3]
Hi,

Thanks for the great work!
I'm wondering if there is any other way to download datasets besides from Baidu? (e.g. Google Drive...)
Thanks in advance!

**Comment by YujieOuO** [comment]
https://github.com/Levigty/AimCLR?tab=readme-ov-file#data-preparation
we used the same data process as AimCLR. You can download all types of skeleton data from their Google Drive.

**Comment by JackChen890311** [comment]
Got it thanks!
