### ISSUE TITLE
How to use the Sentence-bert

### ISSUE THREAD

**Issue by ZeraPeng** [YujieOuO/SMIE#4]
Thank you for releasing your excellent work!
I am interested in generating new semantic features with GPT and processing them with Sentence-Bert. Which model from Sentence Transformer did you use? Could you share the python file of this procedure?
Thanks!

**Comment by YujieOuO** [comment]
I'm sorry the specific file is missing.
maybe you could refer to synse[https://github.com/skelemoa/synse-zsl]
or choose an available version in https://github.com/UKPLab/sentence-transformers

**Comment by ZeraPeng** [comment]
Thank you for your kind response! I have solved this issue.
